In [1]:
import numpy as np 
import pandas as pd 
import xarray as xr

### Task 1

In [2]:
data = xr.open_dataset("waves_2019-01-01.nc")

In [9]:
data_df = data.to_dataframe().reset_index()

In [58]:
data_0_0 = data_df[(data_df['latitude'] == 0.0) & (data_df['longitude'] == 0.0)]

data_0_0

,latitude,longitude,time,hmax,mwd,mwp,tmax,swh
2427840,0.0,0.0,2019-01-01 00:00:00,2.080878,182.493088,7.965504,6.504281,1.102838
2427841,0.0,0.0,2019-01-01 01:00:00,2.078691,182.295319,8.031866,6.585804,1.102607
2427842,0.0,0.0,2019-01-01 02:00:00,2.076502,182.097565,8.096103,6.667326,1.102377
2427843,0.0,0.0,2019-01-01 03:00:00,2.076064,181.888809,8.155851,6.745258,1.103067
2427844,0.0,0.0,2019-01-01 04:00:00,2.077815,181.663574,8.204266,6.809463,1.104678
2427845,0.0,0.0,2019-01-01 05:00:00,2.079565,181.449326,8.252914,6.874722,1.106288
2427846,0.0,0.0,2019-01-01 06:00:00,2.083942,181.235092,8.291882,6.926677,1.109049
2427847,0.0,0.0,2019-01-01 07:00:00,2.090508,180.998871,8.315970,6.965115,1.113191
2427848,0.0,0.0,2019-01-01 08:00:00,2.101013,180.784622,8.340059,6.991726,1.118713
2427849,0.0,0.0,2019-01-01 09:00:00,2.110205,180.564880,8.367455,7.023829,1.123775
2427850,0.0,0.0,2019-01-01 10:00:00,2.120272,180.378098,8.385638,7.038190,1.128606
2427851,0.0,0.0,2019-01-01 11:00:00,2.142157,180.229782,8.351868,6.985390,1.138730
2427852,0.0,0.0,2019-01-01 12:00:00,2.171044,180.147385,8.288812,6.886550,1.151845
2427853,0.0,0.0,2019-01-01 13:00:00,2.194680,180.119904,8.250317,6.824457,1.162658
2427854,0.0,0.0,2019-01-01 14:00:00,2.204747,180.026520,8.263306,6.841776,1.168180
2427855,0.0,0.0,2019-01-01 15:00:00,2.213502,179.817764,8.281490,6.866063,1.172782
2427856,0.0,0.0,2019-01-01 16:00:00,2.233636,179.504639,8.255040,6.820233,1.181985
2427857,0.0,0.0,2019-01-01 17:00:00,2.250706,179.262924,8.184899,6.722238,1.189347
2427858,0.0,0.0,2019-01-01 18:00:00,2.268652,178.960785,8.167896,6.694148,1.197630
2427859,0.0,0.0,2019-01-01 19:00:00,2.279594,178.532303,8.170730,6.693304,1.203612
2427860,0.0,0.0,2019-01-01 20:00:00,2.290975,178.032394,8.171438,6.686756,1.209135
2427861,0.0,0.0,2019-01-01 21:00:00,2.304106,177.510513,8.162464,6.667326,1.215806
2427862,0.0,0.0,2019-01-01 22:00:00,2.319425,176.856796,8.144279,6.635435,1.222939
2427863,0.0,0.0,2019-01-01 23:00:00,2.325991,176.532669,8.156560,6.649586,1.226851

In [59]:
data_0_0['hmax'].values

array([2.0808783, 2.0786905, 2.0765018, 2.076064 , 2.077815 , 2.079565 ,
       2.0839424, 2.0905075, 2.1010132, 2.1102047, 2.1202717, 2.1421566,
       2.1710443, 2.1946802, 2.2047472, 2.213502 , 2.233636 , 2.2507057,
       2.268652 , 2.2795944, 2.2909746, 2.3041058, 2.3194246, 2.3259907],
      dtype=float32)

### Task 2

In [53]:
import requests

In [52]:
url = 'https://europe-west1-freesolarcalc.cloudfunctions.net/wave_max/'
params = {"lat":4.0, "lon":1.3}
res = requests.get(url, params)
print(res.text)

{"2009":4.870349884033203,"2010":4.449041366577148,"2011":5.537721633911133,"2012":5.245943069458008,"2013":5.48573112487793,"2014":5.522931098937988,"2015":5.0021209716796875,"2016":5.170196533203125,"2017":5.556546211242676,"2018":4.7959489822387695,"2019":4.951474189758301}